adding while loop

diff --git a/setup_nagios b/setup_nagios
--- a/setup_nagios
+++ b/setup_nagios
@@ -6,11 +6,25 @@ ip_address=$(ip route get 1 | awk '{print $NF;exit}')
 sed -i "s/^allowed_hosts=127.0.0.1.*/allowed_hosts=127.0.0.1,$ip_address,$nagios_server/" /etc/nagios/nrpe.cfg
 service nagios-nrpe-server restart
 
+n=0
+until [ $n -ge 5 ]
+do
+   sudo service nagios-nrpe-server status > /dev/null && break  # substitute your command here
+   exit_code=$?
+   echo "Waiting for service restart..."
+   n=$[$n+1]
+   sleep 1
+done
+if [ $exit_code -ne 0 ]; then 
+  echo "Service failed to start in the alloted time!"
+  exit $exit_code
+fi
+
 /usr/lib/nagios/plugins/check_nrpe -H $ip_address
 exit_code=$?
 if [ $exit_code -eq 0 ]; then
-    echo "Nagios was set up correctly"
+    echo "\nNagios was set up correctly"
 else
-    echo "Nagios setup failed!"
+    echo "\nNagios setup failed!"
     exit $exit_code
 fi
